apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}{{ .Values.cronjob3.name }}
spec:
  schedule: {{ quote .Values.cronjob3.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: {{ .Release.Name }}{{ .Values.imageCredentials.name }}
          containers:
          - name: {{ .Values.cronjob3.name }}
            image: {{ .Values.cronjob3.image }}
            imagePullPolicy: {{ .Values.cronjob3.imagePullPolicy }}
            env:   # Setting Enviornmental Variables
            - name: KAFKA   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap  # name of configMap
                  key: kafka_producer
          restartPolicy: {{ .Values.cronjob3.restartPolicy }}