apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-svc-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: webapp-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapp-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: webapp-svc-account
  namespace: default
roleRef:
  kind: Role
  name: webapp-role
  apiGroup: rbac.authorization.k8s.io